name: Lint

on:
  push:
    branches:
      - '*'

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install dependencies 🔧
        run: pnpm install --frozen-lockfile

      - name: Lint 🧹
        run: pnpm code-style
